회고:
    - {fileName: 2018년회고}
'spring,':
    - {fileName: 기본적인내용}
    - {fileName: 성능튜닝}
    - {fileName: Async}
    - {fileName: Bean_Validation}
    - {fileName: BeanScope}
    - {fileName: initSpring}
    - {fileName: Spring_Boot}
    - {fileName: Spring-Batch}
    - {fileName: WebFlux}
tip:
    - {fileName: 기본적인내용}
'java,':
    - {fileName: 성능튜닝}
    - {fileName: Interface}
    - {fileName: PostContrunct}
성능:
    - {fileName: 성능튜닝}
'연말정산,공인인증서':
    - {fileName: 연말정산}
regex:
    - {fileName: 정규식}
manager:
    - {fileName: 조직관리}
'airflow,':
    - {fileName: Airflow}
datapipline:
    - {fileName: Airflow}
architecture:
    - {fileName: Architecture}
    - {fileName: MSA}
'async,':
    - {fileName: Async}
task_executor:
    - {fileName: Async}
'bean,':
    - {fileName: Bean_Validation}
validation:
    - {fileName: Bean_Validation}
bean_scope:
    - {fileName: BeanScope}
book:
    - {fileName: Books}
    - {fileName: Refactoring}
codereview:
    - {fileName: CodeReview}
datastructure:
    - {fileName: DataStructure}
devops:
    - {fileName: DevOps}
document:
    - {fileName: Document}
'enum,':
    - {fileName: Enum}
java:
    - {fileName: Enum}
    - {fileName: Java}
    - {fileName: Spring_Boot}
git:
    - {fileName: Git}
'book,':
    - {fileName: GOF_DesignPattern}
designpattern:
    - {fileName: GOF_DesignPattern}
gradle:
    - {fileName: Gradle}
haproxy:
    - {fileName: haproxy}
'hbase,nosql':
    - {fileName: Hbase}
http:
    - {fileName: Http}
infra:
    - {fileName: Infra}
springboot:
    - {fileName: initSpring}
'oop,':
    - {fileName: Interface}
interface:
    - {fileName: Interface}
'json,':
    - {fileName: Jackson}
    - {fileName: JWT}
jackson:
    - {fileName: Jackson}
jpa:
    - {fileName: JPA}
'test,junit':
    - {fileName: JUnit5}
'devops,':
    - {fileName: Jvm}
'jvm,':
    - {fileName: Jvm}
'gc,':
    - {fileName: Jvm}
thread:
    - {fileName: Jvm}
jwt:
    - {fileName: JWT}
'k8s,':
    - {fileName: k8s}
kubernetes:
    - {fileName: k8s}
kafka:
    - {fileName: Kafka}
kotlin:
    - {fileName: Kotlin}
'kotlin,kia,kotlin':
    - {fileName: Kotlin_In_Action}
in:
    - {fileName: Kotlin_In_Action}
action:
    - {fileName: Kotlin_In_Action}
linux:
    - {fileName: Linux}
slf4j:
    - {fileName: Logging}
logstash:
    - {fileName: logstash}
'db,':
    - {fileName: MS-SQL}
    - {fileName: Transaction}
'ms-sql,':
    - {fileName: MS-SQL}
dbms:
    - {fileName: MS-SQL}
'msa,':
    - {fileName: MSA}
mysql:
    - {fileName: MySQL}
'NoSql,redis':
    - {fileName: NoSQL}
'Java,':
    - {fileName: Optional}
optional:
    - {fileName: Optional}
annoatation:
    - {fileName: PostContrunct}
'jpa,':
    - {fileName: QueryDsl}
querydsl:
    - {fileName: QueryDsl}
'mq,':
    - {fileName: RabbitMQ}
    - {fileName: RabbitMQ}
'message,':
    - {fileName: RabbitMQ}
'queue,':
    - {fileName: RabbitMQ}
'rabbit,':
    - {fileName: RabbitMQ}
amqp:
    - {fileName: RabbitMQ}
secure:
    - {fileName: SecureCoding}
sonarqube:
    - {fileName: SonarQube}
'spock,':
    - {fileName: spock}
    - {fileName: Test_Framework}
'test,':
    - {fileName: spock}
    - {fileName: Test_Framework}
tdd:
    - {fileName: spock}
spring:
    - {fileName: Spring}
'springboot,':
    - {fileName: Spring_Boot}
'spring,springboot,actuactor':
    - {fileName: Spring_Boot_Actuator}
'spring,cloud':
    - {fileName: Spring_Cloud}
'spring,test,springboot,junit':
    - {fileName: Spring_Test}
batch:
    - {fileName: Spring-Batch}
'nas,':
    - {fileName: Synology}
synology:
    - {fileName: Synology}
'tdd,':
    - {fileName: Test_Framework}
junit:
    - {fileName: Test_Framework}
transaction:
    - {fileName: Transaction}
webflux:
    - {fileName: WebFlux}
'secure,':
    - {fileName: XSS}
xss:
    - {fileName: XSS}
