회고:
    - {fileName: 2018년회고}
architecture:
    - {fileName: Architecture}
    - {fileName: MSA}
'spring,':
    - {fileName: Async}
    - {fileName: Bean_Validation}
    - {fileName: BeanScope}
    - {fileName: initSpring}
    - {fileName: Spring_Boot}
    - {fileName: Spring-Batch}
    - {fileName: WebFlux}
    - {fileName: 기본적인내용}
    - {fileName: 성능튜닝}
'async,':
    - {fileName: Async}
task_executor:
    - {fileName: Async}
'bean,':
    - {fileName: Bean_Validation}
validation:
    - {fileName: Bean_Validation}
bean_scope:
    - {fileName: BeanScope}
book:
    - {fileName: Books}
    - {fileName: Refactoring}
codereview:
    - {fileName: CodeReview}
datastructure:
    - {fileName: DataStructure}
devops:
    - {fileName: DevOps}
docker:
    - {fileName: Docker}
document:
    - {fileName: Document}
'enum,':
    - {fileName: Enum}
java:
    - {fileName: Enum}
    - {fileName: Java}
    - {fileName: Spring_Boot}
git:
    - {fileName: Git}
'book,':
    - {fileName: GOF_DesignPattern}
designpattern:
    - {fileName: GOF_DesignPattern}
gradle:
    - {fileName: Gradle}
http:
    - {fileName: Http}
springboot:
    - {fileName: initSpring}
'java,':
    - {fileName: Interface}
    - {fileName: PostContrunct}
    - {fileName: 성능튜닝}
'oop,':
    - {fileName: Interface}
interface:
    - {fileName: Interface}
'json,':
    - {fileName: Jackson}
    - {fileName: JWT}
jackson:
    - {fileName: Jackson}
jpa:
    - {fileName: JPA}
'test,junit':
    - {fileName: JUnit5}
'devops,':
    - {fileName: Jvm}
'jvm,':
    - {fileName: Jvm}
'gc,':
    - {fileName: Jvm}
thread:
    - {fileName: Jvm}
jwt:
    - {fileName: JWT}
kafka:
    - {fileName: Kafka}
kotlin:
    - {fileName: Kotlin}
'kotlin,kia,kotlin':
    - {fileName: Kotlin_In_Action}
in:
    - {fileName: Kotlin_In_Action}
action:
    - {fileName: Kotlin_In_Action}
linux:
    - {fileName: Linux}
slf4j:
    - {fileName: Logging}
logstash:
    - {fileName: logstash}
'db,':
    - {fileName: MS-SQL}
'ms-sql,':
    - {fileName: MS-SQL}
dbms:
    - {fileName: MS-SQL}
'msa,':
    - {fileName: MSA}
'NoSql,redis':
    - {fileName: NoSQL}
'Java,':
    - {fileName: Optional}
optional:
    - {fileName: Optional}
annoatation:
    - {fileName: PostContrunct}
'jpa,':
    - {fileName: QueryDsl}
querydsl:
    - {fileName: QueryDsl}
secure:
    - {fileName: SecureCoding}
'spock,':
    - {fileName: spock}
    - {fileName: Test_Framework}
'test,':
    - {fileName: spock}
    - {fileName: Test_Framework}
tdd:
    - {fileName: spock}
spring:
    - {fileName: Spring}
'springboot,':
    - {fileName: Spring_Boot}
'spring,springboot,actuactor':
    - {fileName: Spring_Boot_Actuator}
'spring,cloud':
    - {fileName: Spring_Cloud}
batch:
    - {fileName: Spring-Batch}
'tdd,':
    - {fileName: Test_Framework}
junit:
    - {fileName: Test_Framework}
webflux:
    - {fileName: WebFlux}
'secure,':
    - {fileName: XSS}
xss:
    - {fileName: XSS}
tools:
    - {fileName: 개발환경세팅}
tip:
    - {fileName: 기본적인내용}
성능:
    - {fileName: 성능튜닝}
'연말정산,공인인증서':
    - {fileName: 연말정산}
