devops:
    - {fileName: DevOps}
docker:
    - {fileName: Docker}
'enum,':
    - {fileName: Enum}
java:
    - {fileName: Enum}
    - {fileName: Java}
'json,':
    - {fileName: Jackson}
jackson:
    - {fileName: Jackson}
jpa:
    - {fileName: JPA}
linux:
    - {fileName: Linux}
slf4j:
    - {fileName: Logging}
spring:
    - {fileName: Spring}
'spring,springboot,actuactor':
    - {fileName: Spring_Boot_Actuator}
tools:
    - {fileName: 개발환경세팅}
